Milestone one: Linter-config
davmba/Hello_Microverse pull request #1
Opened 2022-06-28 18:24 UTC by davmba

In this ### Linter Configuration
In this project, we:
- Added html file
- Added css file
- Added test file

2022-06-28 18:53 UTC, Ismailco requested changes
### Hi @davmba,

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 18:53 UTC, Ismailco commented on .github/workflow/linters.yml
> +Skip to content
- [ ] Linter should be set up correctly for this repository, as for now, the linters check doesn't work on Github, kindly fix this

2022-06-28 18:53 UTC, Ismailco commented on .github/workflow/linters.yml
> +56 lines (53 sloc)  1.91 KB
- [ ] You should not modify the linter config file, kindly restore the linters.yml to the original state so the linters are working correctly

2022-06-28 18:53 UTC, Ismailco commented on test.md
> +this file is to be ignored
- [ ] test.md should not be in your Github repo, kindly remove it from GitHub

2022-06-29 11:02 UTC, prolajumokeoni approved these changes
Hi @davmba, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 13:05 UTC, merged